### PR TITLE
Use `getBy`, not `queryBy`, to fail on missing element

### PR DESCRIPTION
**Pull request by sompylasar**
BREAKING CHANGE: The queries will now throw a useful message and fail
the test if the queried element is missing.

### CODE REVIEW

**Comment by sompylasar** [comment]
While working on a PR to add `getCommandWaiter` to `dom-testing-library` as `waitForElements`, I realized that the breaking change I made here is not compatible with the current implementation of `getCommandWaiter` which does not catch exceptions. Somehow this works with my setup of Cypress, both waits for DOM and rejects if not found. I'll work more on this, so stay tuned.

**Comment by sompylasar** [comment]
@kentcdodds Wowow I should have told you explicitly not to merge it yet, sorry. Anyway, it's still experimental, so hopefully won't break anyone's setups. I'm working on adding the waiter to dom-testing-library with some tests to it.

**Comment by kentcdodds** [comment]
No worries. This hasn't been published to npm yet 😉 I want to wait until it's fully tested first.

**Comment by sompylasar** [comment]
For the record, `waitForElement` is being added here: https://github.com/kentcdodds/dom-testing-library/pull/10

**Pull request merged**
